services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfinity\UxBlocks\:
    resource: '../src/'
    exclude:
      - '../src/SymfinityUxBlocksBundle.php'
      - '../src/DependencyInjection/'
